name: ml_env
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.5.1=py39h06a4308_0
  - matplotlib-base=3.5.1=py39ha18d171_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - gym=0.21.0=py39hef51801_1
  - tensorboard=2.8.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.6.0=py39h3da14fd_0
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - pip:
      - mujoco-maze==0.2.0
      - mujoco-py==2.1.2.14
